### ISSUE TITLE
New release checklist

### ISSUE THREAD

**Issue by marcincichocki** [marcincichocki/vue-image-compare#11]
This is a master issue that aggregate smaller things required to get this repo back and running. Since it has been abandoned for a long time, a lot of things are out of date or not existing at all(hello tests)

Things to do before next release:
- [ ] add tests
- [ ] set up CI for tests and automatic deployments to npm
- [ ] review dependencies and update them accordingly
- [ ] merge any PR
